import csv

hashtags = """BrasilDaEsperança		L
bolsonaro		R
Lula13		L
BolsonaroTemRazao		R
BolsonaroNoPrimeiroTurno		R
BolsonaroReeleitoEm2022		R
Bolsonaro22		R
VaiSerNoPrimeiroTurno		R
LulaEoPTUnicaViaJaNoPrimeiroTurno		L
Vote13		L
LulaLadrao		R
EsquerdaNuncaMais		R
Lula		L
CiroTV		N
forabolsonaro		L
BolsonaroPresidenteAte2026		R
LulaEoPTUnicaViaJaNo1ºTurno		L
LulaNo1ºTurno		L
LulaPresidente13		L
PrefiroCiroPresidente12		N
LulaOGritoDeAmorPeloBrasil		L
LulaNoPrimeiroTurnos		L
PrefiroCiro		N
VotoNoCiro		N
CiroOuNulo		N
BrasilComBolsonaro		R
ForaBolsonaroeSuaQuadrilha		L
LulaEoPTjaNo1ºTurno		L
CiroPresidente12		N
ciro2022		N
NEMBOLSONARONEMLULA		N
BolsonaroÉ22		R
SóLulaSalva		L
bandeirabrasileira		R
lulanoeAlckminprimeiroturno13		L
RepudiaLula		R
PTNuncaMais		R
LulaNaCadeia		R
LulaLadraoSeuLugarENaPrisao		R
patriotas		R
JuntosComBolsonaro		R
FechadoComBolsonaro		R
Dia12ComCiro12		N
ptebolsonaroTudoLadrao		N
foraPT		R
foraLulaeBolsonaro		N
BolsonarismoMATA		L
ForaBolsonaroCorrupto		L
ForaBolsonaroGenocida		L
VotoUtilPraDerrotarOInutil		L
Renunciabolsonaro		L
BolsonaroVaiCair		L
bolsonarocorrupto		L
VamosEsperançar		L
LulaEoPT13deFioApavio		L
datapovo		R
LULADRÃO		R
CiroCresce		N
Virada12		N
BolsonaroAte2026		R
BolsonaroPresidenteAte2026		R
CapitaoDoPovoQueVaiVencerDenovo		R
ToComJairDeNovo		R
PeloBemDoBrasil		R
BolsoMito		R
CapitaoDoPovoe22		R
VoteEm1SeLivreDos2		N
Tebetistas		N
Ciristas		N
ForaBolsonaroGenocidaMiliciano		L
BolsonaroMente		L
BolsonaroMentiroso		L
BolsonaroMiliciano		L
BrasilAcimaDeTudoDeusAcimaDeTodos		R
13Lá13Cá		L
NaCasa13Tem		L
TimeDoLula		L
CiroNoSegundoTurno		N
PraQueEsperarÉLulaJá		L
FazOL		L
EuTôComLula		L
TurmaBoa		N
CiroÚnicaVia		N
tanahoradevoceolharprociro		N
PraCimaDeles		L
vote1313		L
EsquerdaSegueEsquerda		L
DireitaSegueDireita		R
SomosTodosPatriotas		R
ChegaDePopulismo		N
ForaBolsonaroESeuBandoDeCriminosos		L
Lulano1o		L
BolsonaroNaCadeia		L
LulaBandido		R
VoteBolsonaro22		R
lulapresidente2022		L
LulaEPTMentem		R
VoteNoTerceiro		N
JairCashback		L
EleNao		L
Bolsonaro		R
LULA		L
TimeLula		L
BrasilDaEsperanca		L
BrasildaEsperança		L
JairBolsonaro22		R
Eleicoes2022		N
Eleições2022		N
BolsonaroReeleitoEm2022		R
Bolsonaro22		R
LulaNo1ºTurno		L
IgualdadePraFazerADiferença		L
BolsonaroNoPrimeiroTurno		R
QueroBolsonaroAte2026		R
vote13		L
CiroNoRatinho		N
BOLSONARO2022		R
PTNuncaMais		R
LulaNo1oturno		L
CNNnasEleições		N
CapitaoDoPovoVaiVencerDeNovo		R
BolsonaroReeleitoNoPrimeiroTurno		R
BolsonaroTemRazao		R
PrefiroCiro		N
BolsonaroNoPrimeiroTurno22		R
13dias		L
LulaNoPrimeiroTurno		L
BolsonaroEmLondres		R
BolsonaroPresidente22		R
13DiasParaVotar13		L
TimeDoLula		L
LulaPresidente13		L
NoMeuVotoNinguemMexe		N
LulaLáMaríliaCá		L
lulaflix		L
Lula13NoPrimeiroTurno		L
VotePreto		L
Lula13		L
VaiSerNoPrimeiroTurno		L
TurmaBoa		N
BolsonaroReeleitoNoPrimeiroTurno2022		R
eleicoes		N
I3rasil		L
PSOLcomLula		L
Ciro12		N
ÉpraSeguirJuntos		L
BrasildeFato		N
CiroPresidente12		N
BolsonaroVagabundo		L
VaiSerNoPrimeiroTurno22		R
Lula2022		L
VOTOutil		L
VamosJuntosPeloBrasil		L
LulaEoPTjaNo1ºTurno		L
PrefiroCiroPresidente12		N
compartilheaverdade		L
eleicao2022		N
Vote21		L
TaNaHoraDeVoceOlharProCiro		N
LulaPresidente		L
FechadosComBolsonaroAte2026		R
Política		N
PrefiroCiro12		N
ForaBolsonaro		L
ChoraPetezada		R
LulaLadraoSeuLugarENaPrisao		R
PraTodoseTodasVerem		L
forafamilicia		L
PorIssoVotoNoCIRO		N
FazoL		L
LulaPresidente2022		L
JairBolsonaro		R
Ciro2022		N
faltam13		L
Lula13no1oTurno		L
13DiasPraVotar13		L
ForaBolsonaroCorrupto		L
PT13		L
PesquisaEleitoral		N
CriançasPetistas		L
tchutchucadocentrão		L
AuxilioGás		R
FechadoComBolsonaro22		R
13confirma		L
Eleicoes22		N
BolsonaroGenocida		L
ForaBolsonaroGenocida		L
BOLSOANRO		R
jair_bolsonaro		R
VittarloversComBolsonsro		R
13rasil		L
NaoVotemNeles		N
LulaAlckmin		L
FuckBolsonaro		L
LulaNaoEinocenteBabaca		R
oLeDeLadrao		R
DesculpasDoPT		R
brasilfelizdenovo		L
LulaPresidente		L
BolsonaroReeleitoEm2022		R
Bolsonaro22		R
Bolsonaro22ReeleitoNoPrimeiroTurno		R
DebateNoSBT		N
BolsonaroNoPrimeiroTurno		R
FazoL		L
DebatePresidente		N
BrasilComBolsonaro22		R
LulaNo1oturno		L
LulaEmMadureira		L
VOTEJB22		R
LulaNo1ºTurno		L
JairBolsonaro22		R
BolsonaroNoPrimeiroTurno22		R
Eleições2022		N
Eleicoes2022		N
bolsonaro		R
ViraVoto		L
Eleicoes		N
Eleições		N
BolsonaroReeleitoNoPrimeiroTurno		R
BrasilDaEsperanca		L
LulaPresidente13		L
BrasilDaEsperança		L
LulaNoPrimeiroTurno		L
LulaArregão		R
LulaArregao		R
bolsonarocorrupto		L
EsseEmeuVoto		N
EsseÉMeuVoto		N
LulaEoPTtudoNoPrimeiroTurno		L
LulaPeloBrasilHaddadPorSP		L
Eleicao2022		N
Lula13Presidente		L
CiroPresidente12		N
CiroGomes		N
elasim		N
LulaNaPortela		L
VaiSerNoPrimeiroTurno		N
BolsonaroReeleito		R
Lula		L
PrefiroCiro12		N
LulaPrimeiroTurno		L
Ciro12		N
LulaPressidente13		L
bolsonarismo		R
LulaLadrão		R
LulaLadrao		R
Ciro12Presidente		N
Ciro		N
vote13		L
Lula13		L
ForaBolsonaro		L
LulaLáDécioAqui		L
VoteBolsonaro22		R
turmaboa		N
Bolsonaro2022		R
LulaInRio		L
TimeLula		L
PrefiroCiro		N
faltam7		L
EsseEoMeuVoto		N
SimonePresidente15		N
LulaPresidente2022		L
Dia_2_é_BOLSONARO_22		R
lula2022		L
cironaro		R
SomosTodosCapitaoJB22		R
PTNuncaMais		R
LULADRÃO		R
LuLADRAO		R
faltam7dias		L
ForaBolsonaroeSuaQuadrilha		L
LulaNo1ºTurno13		L
Lulabundao		R
AcordaBrasil		R
VotoUtilDerrotaoInutil		L
Lula13NoPrimeiroTurno		L
LulaLADRAOseulugarÉnaPRISÃO		R
ForaBolsonaroCorrupto		L
AgoraEQueSaoElas		N
BolsonaroReeleito2022		R
FuturoPresidiário		L
PrefiroCiroPresidente12		N
CiroOuNulo		N
CiroContraOSistema		N
Dia1VaiSerGigante		R
LulaCovarde		R
foragenocida		L
ForaBolsonaroVagabundo		L
sorayatraira		R
lulaefreixo		L
13livrosvermelhos		L
ÉCiroouNulo		N
BolsonaroNuncaMais		L
VotoUtilPraDerrotarOInutil		L
LuaNo1		L
Luladeprimeira		L
foralulaeBolsonaro		N
Eleicao2022		N
PTNuncaMais		R
BolsonaroNoPrimeiroTurno		R
Eleições2022		N
Eleicoes2022		N
Eleiçoes2022		N
viravoto		L
BolsonaroPresidente22		R
lula2022		L
CNNnasEleições		N
CNNNASELEICOES		N
LulaNoPrimeiroTurno13		L
LulaNo1oturno		L
bolsonaro		R
Bolsonaro22		R
VOTEJB22		R
BolsonaroNoPrimeiroTurno22		R
ELEIÇÕES		N
eleicoes		N
Lula		L
PazNasEleicoes		N
LulaPresidente		L
BrasilComBolsonaro		R
BolsonaroReeleito		R
BolsonaroTemRazao		R
BrasilDaEsperanca		L
BrasilDaEsperança		L
LulaPresidente13		L
vote13		L
VOTE13		L
Lula13		L
FechadoComBolsonaroAte2026		R
ForaBolsonaro		L
UOLEleições2022		N
SimonePresidente15		N
TurmaBoa		N
ForaBozo		L
elenao		L
VaiSerNoPrimeiroTurno22		N
LulaPresidente2022		L
TimeDoLula		L
votoimpressoauditável		R
CiroContraOSistema		N
PSOLcomLula		L
BolsonaroReeleito2022		R
Lula13Presidente		L
EsquerdaCriminosa		R
NortecomLula		L
ViolênciaPolítica		N
VamosEsperançar		L
LulaOGritoDeAmorPeloBrasil		L
SBTEleições2022		N
EsseEoMeuVoto		N
esquerda		L
TaNaHoraDeVoceOlharProCiro		N
BolsonaroReeleitoEm2022		R
SomosTodosCapitaoJB22		R
Bolsonaro22em2022		R
NordesteComBolsonaro		R
LulaLadraoSeuLugarENaPrisao		R
LuizInácioLuladaSilva		L
VOTOIMPRESSOJÁ		R
LulaNuncaMais		R
CiroPresidente12		N
NEMBOLSONARONEMLULA		N
PrefiroCiroPresidente12		N
ForaBolsonaroeSuaQuadrilha		L
LulaArregao		R
CentraldasEleições		N
PrefiroCiro		N
13neles		L
CapitaoDoPovoQueVaiVencerDenovo		R
BolsonaroÉ22		R
ciro		N
LulaNão		R
EuTôComLula		L
vote		N
BandEleicoes		N
ciro2022		N
LULALA		L
CiroGomes		N
FazoL		L
Lula13no1oTurno		L
ForaBolsonaroVagabundo		L
LULADRÃO		R
Luladeprimeira		L
AcordaBrasil		L
ToComJairDeNovo		R
LULAPRESIDENTE22		L
bolsonaronao		L
GloboLixo		R
Nulo2022		N
AmazonascomoBolsonaro		R
ÉpraSeguirJuntos		R
Brasil2022		N
porlulaepelonordeste		L
Tebet2026		N
ForaLulaLadrao		R
VotoUtilDerrotaoInutil		L
lulinha		L
quemanulavotalula		R
CollorministrodoBolsonaro		L
LulaPresidente1️⃣3️⃣		L
Bolsonaro22		R
LulaEmBH		L
BrasilDaEsperanca		L
BrasilDaEsperança		L
lula2022		L
Eleicoes2022		N
Eleições2022		N
LulaNoSegundoTurno		L
bolsonaro		R
Bolsonaro2022		R
nordestecomlula		L
BolsonaroReeleito22		R
OrçamentoSecreto		L
DITADURANAO		R
FechadoComBolsonaro		R
LulaNuncaMais		R
BrasilComBolsonaro22		R
BolsonaroReeleito		R
BolsonaroPresidente22		R
PTNuncaMais		R
B22		R
Lula13		L
ForaLula		R
Votar13		L
forabolsonarogenocida		L
Vote13		L
NordesteComBolsonaro		R
AgoraÉLula13		L
BolsonaroCanibal		L
BolsonaroPresidente		R
Eleicao2022		N
BolsolaoDoAsfalto		L
SimoneTebet		L
BrasilVota22		R
LulaPresidente13		L
BolsonaroPresidente2022		R
VoteBolsonaro22		R
EsquerdaSegueEsquerda		L
foraBolsonaro		L
BolsonaroReeleito2022		R
LulaNo1ºTurno		L
VOTE22		R
Lula		L
LulaLadrão		R
lulamente		R
VamosJuntosPeloBrasil		L
SimoneTebet2022		L
BolsonaroSatanista		L
eleições		N
eleicoes		N
BolsonaroMentiroso		L
bolsonarocorrupto		L
lulapresidente2022		L
BolsonaroNoPrimeiroTurno		R
LulaNo2ºTurno		L
LulaNaCadeia		R
CNNnasEleições		N
ForaBolsonaroCorrupto		L
ForaBolsonaroESuaQuadrilha		L
VotoNulo		N
NordesteBolsonaro		R
BolsonaroReeleitoEm2022		R
simone		L
BolsonaroMente		L
urnaeletrônica		N
patriotas		R
LulaLadraoSeuLugarENaPrisao		R
LulaLADRAOseulugarÉnaPRISÃO		R
ciro		L
DitaduraNuncaMais		L
conectividadecomLuLa		L
fascistas		L
alckmin		L
22Neles		R
NinguémSoltaAMaoDoLula		L
BrasilAcimaDetudoDeusAcimaDeTodos		R
BolsonaroNaCadeia		R
Bolsolao		L
BolsonaroNaoEcristao		L
esquerdalhasnuncamais		R
lulinha		L
BolsonaroMeRepresenta		R
bolsominions		L
Bolsonaroumneuronio		L
brasillula		L
ForaBolsonaroVagabundo		L
DeusFamiliaPatriaLiberdade		R
bolsolaodomec		L
VotoEmCédula		R
Collor		L
cirogomes		L
ViraVotoPraBolsonaro		R
LuLADRAO		R
BolsobaroEleitoSegundoTurno		R
CensuraDoPTNao		R
BolsonaroReleito2022		R
BolsolaoDoViagra		L
CollorministrodoBolsonaro		L
Bolsonaro22		R
bolsonaro		R
DITADURANAO		N
lulanuncamais🎯		R
LulaNuncaMais		R
BrasilComBolsonaro22		R
BolsonaroPresidente2022		R
Eleições2022		N
Eleicoes2022		N
eleicoes		N
eleições		N
VOTE22		R
BolsonaroMentiroso		L
Vote13		L
BrasilDaEsperança		L
BrasilDaEsperanca		L
LulaPresidente1️⃣3️⃣		L
SimoneTebet		L
lulinha		L
PTNuncaMais		R
BolsonaroReeleito22		R
Eleicao2022		R
B22🇧🇷		R
FechadoComBolsonaro		R
ForaLula		R
B22		R
BolsonaroReeleito		R
Votar13		L
LulaNo2ºTurno		L
LulaPresidente13		L
BolsolaoDoAsfalto		L
lulamente		R
BolsonaroNoPrimeiroTurno		R
BolsonaroNaCadeia		L
VotoEmCédula		R
CNNnasEleições		N
NordesteComBolsonaro		R
VamosJuntosPeloBrasil		L
tse		N
BolsonaroPresidente22		R
DeusFamiliaPatriaLiberdade		R
Lula13		L
LulaLadrão		R
LulaNoSegundoTurno		L
OrçamentoSecreto		L
SimoneTebet2022		L
BolsonaroMente		L
lulapresidente2022		L
LulaEmBH		L
BolsonaroReeleito2022		R
Lula		L
foraBolsonaro		L
BolsonaroReeleitoEm2022		R
DitaduraNuncaMais		N
ForaBolsonaroESuaQuadrilha		L
EsquerdaSegueEsquerda		L
ciro		L
LulaNo1ºTurno		L
VoteBolsonaro22		R
Globolixo		R
forabolsonarogenocida		L
AgoraÉLula13		L
bolsominions		L
BolsolaoDoViagra		L
BrasilVota22		R
BolsonaroCanibal		L
lula2022		L
Bolsolao		L
cirogomes		L
NinguémSoltaAMaoDoLula		L
nordestecomlula		L
urnaeletrônica		R
LulaNaCadeia		R
Collor		L
Bolsonaro2022		R
BolsonaroNaoEcristao		L
22Neles		R
VotoNulo		N
NordesteBolsonaro		R
esquerdalhasnuncamais		R
ForaBolsonaroVagabundo		L
CensuraDoPTNao		R
LuLADRAO		R
marinasilva		L
ForaBolsonaroCorrupto		L
fascistas		L
bolsolaodomec		L
LulaLADRAOseulugarÉnaPRISÃO		R
LulaLadraoSeuLugarENaPrisao		R
patriotas		R
alckmin		L
Bolsonaroumneuronio		L
conectividadecomLuLa		L
BolsonaroSatanista		L
minibolsominion		L
BolsonaroMeRepresenta		R
brasillula		L
quemanulavotalula		R
BolsonaroReleito2022		R
LulaLadrao		R
LulaLadrão		R
eleicoes		N
Eleições2022		N
eleições2022		N
Eleicoes2022		N
lula13		L
Lula13		L
eleicoes2022		N
SuperLiveBolsonaro22.		R
SuperLiveBolsonaro22🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷🇧🇷		R
EquipeLula		L
Bolsonaro22		R
Eleiçoes2022		N
BolsonaroReeleito2️⃣2️⃣		R
SuperLiveBolsonaro22		R
BolsoNey		R
VamosJuntosPeloBrasil		L
BolsonaroReeleito22		R
LulaNoFlow		L
BrasilDaEsperança		L
jairbolsonaro		R
bolsonaro		R
SuperLiveBolsonaro		R
Vote13		L
SuperLiveComBolsonaro22		R
LULA13PRESIDENTE		L
LulaPresidente1⃣3️⃣		L
forafascistas		L
lulapresidente		L
Bolsonaro2022		R
bolsonaro2022		R
LulaNuncaMais		R
LulaPresidente		L
22		R
LulaPresidente1️⃣3️⃣		L
LulaPresidente1⃣3⃣		L
lula		L
SuperLiveComBolsonaro		R
BolsonaroPresidente22		R
ptnuncamais		R
PTNuncaMais		R
Lula		L
bolsonaronaomexanomeusalario		L
BolsonaroNãoMexaNoMeuSalário		L
AgoraÉSó13		L
BOLSONARONÃOMEXECOMMEUSALÁRIO		L
ViraVoto		L
Bolsonaro		R
Dia30VoteBolsonaro22		R
BolsonaroReeleitoEm2022		R
Lula13BrasilSemOdio		L
presidentebolsonaro22		R
13		L
fazoL		L
capitaodopovo		R
esquerda		L
LiveDoBolsonaro		R
partidodostrabalhadores		L
BolsonaroNaCadeia		L
LulaPresidente13		L
b17		R
ForaBolsonaro,		L
forabolsonaro		L
ForaBolsonaro		L
Eleição2022		N
bolsonaroreeleito2022		R
EsquerdaMentirosa		R
MulheresComLula		L
forabozo		L
Bolsonaro22ViraVira		R
vidasnegrasimportam		L
voltalula		L
ForaBolsonaroGenocida		L
pt		L
LulaPresidente2022		L
lula2022		L
ForaBolsonaroeSuaQuadrilha		L
genocida		L
VotoNulo		N
Lula2022		L
lula2023		L
direita		R
EleNão		L
jairmessiasbolsonaro		R
ForaBolsonaroPedófilo		L
brasilacimadetudo		R
cadavotoconta		R
SuperLiveDaLiberdade		R
ForabolsonaroAnticristo		L
LulaNoDLShow,		L
LulaNoDLShow		L
bolsominion		L
bozo		L
LulaPresidente20221️⃣3️⃣		L
expresidiario		R
semanaquevemlulapresidente		L
EsquerdaNuncaMais		R
Bolsonaronaomexanasaposentadorias		L
VotarBolsonaroEVergonha		L
Lula13		L
LulaBrasil		L
ELEICOES2022		N
Eleições2022		N
Eleicoes2022		N
eleições2022		N
22🇧🇷		R
LulaPresidente2022		L
Eleicao2022		N
eleicoes2022		N
VoteLula13		L
BolsonaroPresidente22		R
13		L
Voto13		L
lulapresidente		L
LulaPresidente		L
LULAPRESIDENTE		L
BolsonaroReeleito		R
vote13		L
BolsonaroReeleito2️⃣2️⃣		R
reeleicao		R
LulaDay		L
eleições		N
eleicoes		N
Lula		L
lula		L
LULA		L
VoteBolsonaro22		R
CNNnasEleições		N
LulaPresidente1️⃣3️⃣		L
lulalivre		L
simonetebet		L
forabolsonaro		L
ForaBolsonaro		L
hojee13		L
LulaLadrao		R
BolsonaroNuncaMais		L
fazoL		L
LulaPresidente1⃣3️⃣		L
Eleicao		N
nordestevota13		L
Bolsonaro2022		R
SemMedoDeSerFeliz		L
BolsonaroReeleitoEm2022		R
Bolsonaro		R
BOLSONARO		R
ForaLulaLadrao		R
LulaNoSegundoTurno		L
Lula13Presidente		L
LulaLadraoSeuLugarENaPrisao		R
voto		N
LULAOAMORVENCEU		L
BolsonaroPresidente2️⃣2️⃣		R
paidamentira		N
Eleicoes22		N
bolsonaro		R
JairBolsonaro		R
jairBolsonaro		R
lula2022		L
LULA2022		L
Lula2022		L
PazNasEleicoes		N
elenãomerepresenta		R
esquerda		L
LulaPresidente1⃣3⃣		L
LulaPresidente20221️⃣3️⃣		L
BolsonaroPresidente		R
Mito		R
eleicoesbrasil		N
ForaBolsonaroVagabundo		L
lulapresidente2023		L
JairBolsonaroPresidente22		R
PL		R
LulaMentiroso		R
lulasafado		R
VOTANORDESTE		L
VaiDarPT		L
capitaobolsonaro22		R
votei13		L
LULALA		L
EleNao		L
elenão		L
ForaBolsonaroeSuaQuadrilha		L
nordesteé13		L
tebet		L
DesculpasDoPT		R
vermelhou		L
PresidênciaBrasil2022		N
LULAEUTEAMO		L
ForaTchuTchucaDoCentrão		L
13neles		L
boralula		L
ELEIÇÕESVOTE		N
bolsonaropedofilo		L
presidente		N
VotoNulo		N
EsquerdaNuncaMais		R
VotarBolsonaroEVergonha		L
semanaquevemlulapresidente		L
cadavotoconta		R
ForaLula		R
foralula		R
LulaLadrao		R
CensuraNao		R
BrasilComBolsonaro		R
eleicoes2022		N
ptnao		R
fraude		R
conservadores		R
INTERVENCAOFEDERALJA		R
ForaLulaLadrao		R
grevegeral		N
ciro		L
LulaPresidente1️⃣3️⃣		L
ForcasArmadasSalvemOBrasil		R
FORALADRAO		R
lula2022		L
lulanuncamais		R
13		L
BolsonaroReeleito2️⃣2️⃣		R
PTNuncaMais		R
LulaVergonhaNacional		R
LulaNao		R
bolsonaro		R
Bolsonaro		R
forapt		R
EfeitoLula		L
DireitaUnida		R
SOSForcasArmadasSalvemOBrasil		R
lula		L
BolsonaroPresidente22		R
bolsonaristas		L
JairQuebrouOBrasil		L
NovoGovernoLula		L
alexandredemoraesditador		R
ImpeachmentDoLula		R
Eleiçõestransparentes		R
LulaPresidenteDoBrasil		L
AlexandreDeMoraesNaCadeia		R
todoscombolsonaro		R
LulaLadraoSeuLugarENaPrisao		R
LulaNaCadeia		R
TodoPoderEmanaDoPOVO		R
BrasilDaEsperança		L
patriotadocaminhao		L
direitaconservadora		R
bolsominions		L
bolsonaropresidente		R
forabolsonaro		L
ForaBolsonaro		L
LulaPresidente20221️⃣3️⃣		L
LulaEleito		L
LulaPresidente		L
LulaNoMundo		L
NaoCompreDeEsquerdistas		R
jairbolsonaroreeleito		R
esquerdista		L
LadraoNaPresidenciaNao		R
LulaPresidente1⃣3⃣		L
fazoL		L
MidiaLixo		R
bolsonarista		L
fazoLdeladrao		R
cadeosvotos		R
bolsonaropedofilo		L
NossaBandeiraJamaisSeraVermelha		R
JairBolsonaro		R
ForaBolsonaroeSuaQuadrilha		L
lulalá		L
DitaduraNao		R
bolsonaroFaliuOBrasil		L
PatriotasTamosJuntosBrasil		R
Brasilfoiroubado		R
BolsonaroNaCadeia		L
ImpeachAlexandreJÁ		R
corrupcaovoltou		R
forabolsonaropedófilo		L
petista		R
MidiaVendida		R
eduardobolsonaro		R
intervencaoFederalHOJE		R
Patriotas		R
forabolsonarovagabundo		L
esquerdaliberta		L
ondeestaonossovoto		R
queremosaprova		R
foraluladrão		R
TANAHORADOJAIREMBORA		L
fazoLimediatamente		L
MoraesTirano		R
intervencaoMilitar		R
RadiolaoDoPT		R
STFVergonhaNacional		R
OLulaFoiEleitoBabaca		L
eleiçõessbrasil2022		N
LulaPresidente2022		L
direitista		R
DesculpasDoPT		R
GreveGeralNao		L
LulaPresidenteObrigadoBrasil		L
impeachmentJa		R
eleicoes2022		N
brasilnasruas		R
BrasilNasRuas		R
TodosPeloBrasil		R
SOSFORCASARMADAS		R
LulaVergonhaNacional		R
bolsonaro2022		R
globolixo		R
LulaLadraoSeuLugarENaPrisao		R
BolsonaroPresidente		R
DeusPatriaFamiliaLiberdade		R
bolsonaro		R
STFNaoMeRepresenta		R
LulaNaCop27		L
PatriotasNasRuas		R
PTNuncaMais		R
STFOrganizacaoCriminosa		R
forabolsonaro		L
lula13pelavidapelobrasil		L
Lula		L
lulaladrao		R
100%Bolsonaro		R
OAmorVenceu		L
LulaNaCop		L
LulaNaCOP		L
IntervencaoFederalMilitar		R
quemmandoumatarbolsonaro		L
BrasilDoFuturo		L
ditaduranuncamais		N
FFAAsalvemOBrasil		R
lula2022		L
LulaMeuPresidente		L
INTERVENCAOFEDERALJA		R
outLula		R
sosforcasarmadassalvemobrasil		R
LulaPresidente20221️⃣3️⃣		L
RespeiteMeuVoto		L
BolsonaroReeleito2️⃣2️⃣		R
lulapresidente13		L
LulaPresidente1️⃣3️⃣		L
DireitaSegueDireita		R
LulaPresidente		L
AquinãosefalamaldoLula		L
EstouComBolsonaro		R
SalvemOBrasil		R
LadraoNaPresidenciaNao		R
ForaBolsonaroeSuaQuadrilha		L
foralulaladrão		R
lulanão		R
eleições		N
BolsonaroNaCadeia		L
simonetebet		L
BolsonaroNuncaMais		L
LulaPresidente2022		L
MelhorJairSeAcostumando		R
LulaEleito		L
BrazilWasStolem		R
brazilwasstolenbybolsonaro		L
Luladrão		R
SomosTodosBolsonaro		R
CiroGomes		L
ForaGlobo		R
stftraidoresdapatria		R
Transiçãodegoverno		L
JuntosSomosMaisFortes		R
LulaNoEgito		L
lulanuncamais		R
EuSouConservador		R
cadeobolsonaro		L
LulaPresidenteELEITO		L
fraudenasurnas		R
LulaPresidenteEleito		L
LulaLiderMundial		L
forapt		R
LulaPresidenteDoBrasil		L
ForaLula!		R
politicodeestimacao		L
Lulamaníacosexual		R
Bolsonaroehoradedizertchau		L
lulanaomereprenta		R
DesculpasDoPT		R
bolsonarovagabundo		L
ForaLula		R
BrasilRigged		R
22bolsonaro		R
FazoL		L
bolsomito		R
LulaEstadista		R
aceitaquedoimenos		L
quadrilhadopt		R
calandobolsominios.		L
intervencaofederal		R
foralula		R
democraciavive		L
presidentebolsonaro		R
LulaNAOSobeARampa		R
PetistaNãoTemConsciência		R
PatriotaBrasilJB		R
LulaPelaVida		L
"""

caracterized = dict()
caracterized_r = dict()
caracterized_n = dict()
caracterized_l = dict()


for linha in hashtags.splitlines():
    linha = linha.split()
    caracterized[linha[0]] = linha[1]
    if linha[1] == 'R':
        caracterized_r[linha[0]] = linha[1]
    elif linha[1] == 'L':
        caracterized_l[linha[0]] = linha[1]
    else:
        caracterized_n[linha[0]] = linha[1]

print(len(caracterized_r.keys()))
print(len(caracterized_l.keys()))
print(len(caracterized_n.keys()))

nome_do_arquivo = 'man_carac_hashtags.csv'
# Abre o arquivo CSV em modo de escrita
with open(nome_do_arquivo, 'w', newline='', encoding='utf-8') as arquivo_csv:
    escritor_csv = csv.writer(arquivo_csv)

    # Escreve cada item do dicionário em uma linha separada
    for chave, valor in caracterized.items():
        escritor_csv.writerow([chave, valor])

print(f'O arquivo {nome_do_arquivo} foi criado com sucesso.')
